server:
  port: 8083

spring:
  cloud:
    gateway:
      globalCors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowedCredentials: false
      discovery:
        locator:
          enabled: true
      routes:
        - id: logbook-service
          uri: lb://logbook-service
          predicates:
            - Path=/logbook/**
        - id: productcatalog-service
          uri: lb://productcatalog-service
          predicates:
            - Path=/product/**
        - id: shoppingcart-service
          uri: lb://shoppingcart-service
          predicates:
            - Path=/shoppingcart/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
